### ISSUE TITLE
Wrongly defined pin in chip 32MZ2064DAS176

### ISSUE THREAD

**Issue by Rielynd** [Microchip-MPLAB-Harmony/dev_packs#1]
I noticed that Pin 81 (RD13) from this chip is not correctly defined.

[This](https://pasteboard.co/IrStGDC.png) is how the pin is being described as in the datasheet,
[this](https://pasteboard.co/IrSuiSd.png) is how the pin is being shown in MHC.

Found [this](https://pasteboard.co/IrSvTzy.png) in the chip's edc file.

**Comment by aethaniel** [comment]
fixed by #c5dd7a70cdb59ae039639cee87e0df62ac3c7045
