### ISSUE TITLE
Question: New version of the MCAL compatible with v3.3.0

### ISSUE THREAD

**Issue by usmanimtiaz63** [Microchip-MPLAB-Harmony/dev_packs#2]
Hi,
Is there a new version of the MCAL for **_samv71b_** associated with the versions after v3.2.1 as they do not have instance folder and previous MCAL use it?
Thanks

**Comment by aethaniel** [comment]
@usmanimtiaz63, this isn't the right place to ask that kind of question as it isn't related to Harmony.
The DFPs here are only for Harmony purpose while the mainstream is either http://packs.download.microchip.com/ (new versions for Microchip ecosystem, present here) or http://packs.download.atmel.com/ (legacy versions for Atmel ecosystem). You are referring to the latter.
Please go to http://support.microchip.com.
